name: Check Types

on:
  pull_request: ~

  push:
    branches:
      - main

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm lint:types
